### ISSUE TITLE
体验之后发现的一些问题和建议

### ISSUE THREAD

**Issue by Runtu4378** [yautah/dva-wxapp#1]
## 问题

- 页面在初始化获取 connect 来的 state 之前没有初始化 Page.data。在 wxml 中有用到 image 组件，而这个组件的图片地址是由未初始化的 Page.data 中引用的时候会触发渲染层错误：

> Thu Aug 31 2017 16:29:45 GMT+0800 (中国标准时间) 渲染层网络层错误
VM119:2 Failed to load image http://950855194.debug.open.weixin.qq.com/pages/index/index : the server responded with a status of 404 (HTTP/1.1 404 Not Found) 
From server 127.0.0.1

Page.data 的初始化和 model 的 data 的内容未必相同，可能要考虑下比较好的解决方案。

## 建议

小弟我也在寻找比较好的以 redux 为框架的小程序解决方案，[好奇心日报Demo](https://github.com/qixiuss/wxapp-redux-starter) 是我现在遇到的比较好的解决方案，特点是对小程序本身的 templete 的文件维度的单独封装和相应方法隔离和引用提供了解决示例，less转wxss、xml转wxml等比较实用的解决方案，不过可惜作者最近没有更新。我在 loading 态的处理上遇到了需求，所以就找到了这里 0.0

各路大神也多多指教哈

**Comment by yautah** [comment]
可否描述的更清楚些或者给段示例代码展示一下问题？

**Comment by Runtu4378** [comment]
## 问题描述，在 Page 的 data 未有初始数据（如默认显示的图片地址）时，image 组件会触发“渲染层网络层错误“ 原因是没有相应的图片地址被输入，所以触发了一次错误，在 data 被赋值了之后才会显示相应的图片，这就要求需要默认配置 data 了，或者对需要有内容才显示的组件添加 wx:if 标签

经测试，是 userinfo 没有初始值导致的，使用以下代码可以取消报错（但实际是 user model 的 state 没有初始值导致的，给 user 的 model 设置初始的 state 应该可以避免这种错误）这种mapStateToData 的方式应该是可靠的 之前是我没有进一步测试才没发现， 不好意思

```javascript
// src/pages/index/index.js - 5
const page = mergeOptions({
  data: {
    userInfo: {
      avatarUrl: '../../images/avatar.png'
    },
  },
  onLoad(options) {
     this.queryWeather();
  },

  onShow(options) {
    console.log('onshow ', options);
  },

  onReady() {
  },
},carousel);
```

**Comment by Runtu4378** [comment]
@yautah 大兄弟 我想问一下 dva-core 能不能引入 dva-loading 吖，我尝试了下都没能引进去

**Comment by yautah** [comment]
page中的data，实际在model中的state中声明，应该是个更好的方式
在page config中声明再merge也行，但是不推荐
应该统一纳入到model中管理

**Comment by yautah** [comment]
dva-loading应该很好弄才是
一会我看看

**Comment by Runtu4378** [comment]
嗯嗯 受教了

dva-loading 我现在在action里面能看到 不过在mapState 函数里面取不到

**Comment by yautah** [comment]
```javascript

//app.js里面
dvapp.use(createLoading({ effects: true }));

//page/index/index.js里
const mapState = ({index, loading}) => {
  return {
    ...index,
    loading,
  };
};

```javascript

然后在看小程序ide里面的appData
你没有map loading state

**Comment by Runtu4378** [comment]
嗯嗯 晓得 

是有的

**Comment by yautah** [comment]
多反馈bug
这个dva集成用起来理论上没问题
还得实测

**Comment by Runtu4378** [comment]
嗯嗯 我也用在重构自己的一个项目上 有问题多多交流

**Comment by lhr000lhr** [comment]
有没有基于wepy的模板呢
